### ISSUE TITLE
What about SockerCluster on UE4 4.23?

### ISSUE THREAD

**Issue by treilhes** [ziicreater/socketcluster-client-ue4#2]
Hello,
First, thanks for this awesome project.
Do you plan to support the new version of UnrealEngine 4.23?
What about Linux support?

**Comment by SloppyShovel** [comment]
Hi,

You are welcome, we are glad you find the project useful.

Yes, 4.23 version will be released today.

**Comment by SloppyShovel** [comment]
Update.

Support for 4.23 is released, and currently under review for marketplace release.
