### ISSUE TITLE
Connecting in Non play mode

### ISSUE THREAD

**Issue by tonymrakovcic** [ziicreater/socketcluster-client-ue4#7]
Hello, and sorry for so many issues, I just like it and would like to use it in a project :D 

I need the plugin to work in editor mode in c++, and it doesn't seem to behave.
I literally call the same function on this button and on begin play.
In BeginPlay, i get a server connection, when not in play mode, I do not get a connection.

Basically I have this situation I want to acomplish. I have already done it with vanilla websockets, so I know it can work

![image](https://user-images.githubusercontent.com/3583441/87161880-6bbb3c00-c2c5-11ea-9a66-277c72e6f145.png)

When in play mode, everything works fine and as imagine.
The main problem is I don't get any error, it simply does not connect.

I suspect this has something to do with the ``const UObject* WorldContextObject,˛`` passed to ``USCClient::Create(`` but I am not sure about this. I have tried following the code, and break it intentionally and I get an error "no world found"
I have tried to put ``GetOwner()``, ``GetWorld()``,  ``this`` and all kinds of other stuff but to no avail.

Is this behaviour something that is known?

Thank you in advance

**Comment by SloppyShovel** [comment]
Where are you creating the client from?

It has to be an object that is located in the world, the reason is Timers are connected to the world, at least timers that can be located at a later date are, socketcluster requires this for ack timer out (no response from server)

If there is no world the client can't be created.

**Comment by tonymrakovcic** [comment]
From a component attached to an actor(cinecamera), i think that has a valid world even if it's not in play mode?

**Comment by SloppyShovel** [comment]
Oke but when you are saying not in play mode, means you are not starting the game at all, your not starting a session ?

**Comment by tonymrakovcic** [comment]
Im in editor mode, and the game is stopped, if I click play it works, if not it doesn't.
So is it designed not to work that way? I don't really use the timers even, i just need to send and receive messages to a server.
Can you atleast point me to the piece of code which fails? Since there is actually no error.
The use case is setting properties with a external control panel, which seems like a reasonably straight forward use of sockets :)

**Comment by SloppyShovel** [comment]
Yes that's the problem you are in Editor Mode, World is created in game not in the editor, sockcluster is not designed for that, the timers are required for ACK, which means server timeout when the server shutsdown or crashes, RPC call etc.. it's part of the framework.

I understand that it's a reasonably straight forward use of sockets, but socketcluster is not websockets, it's a framework build to be used within the framework, it has functionality that standard sockets don't have. that said.

You would have to customize the whole framework.

1. You would have to remove this code where it checks if the World exists
https://github.com/ziicreater/socketcluster-client-ue4/blob/2591c31e1c06fdec7e3e216985f7c8dc5e978a5e/SocketCluster/Source/SCClient/Private/SCClientSocket.cpp#L145

2. Remove every timer and timeout function

3. Remove every Timer Manager function
`GetWorld()->GetTimerManager().SetTimer` 

It's going to be a lot of customization and not really where this framework is meant for if you simply only want to set properties you are better off coding something simpler, you could use the source code of socketcluster, but only bare-bones, like the websocket part written on top of LibWebsockets it's separated module 
https://github.com/ziicreater/socketcluster-client-ue4/tree/2591c31e1c06fdec7e3e216985f7c8dc5e978a5e/SocketCluster/Source/SCSocket

**Comment by tonymrakovcic** [comment]
Hmm, ok.
The main thing that puzzles me here is that it doesn't throw this error if I'm in editor mode - 		USCErrors::InvalidActionError("Unable to access current game world.");

I goes through, it just doesn't connect.
Are you sure there isn't a world in editor?
A fast check 
```
    UWorld* world = GetWorld();
    UE_LOG(LogTemp, Warning, TEXT("Is there a world?  %d"),  world != nullptr);
```
outputs 
``LogTemp: Warning: Is there a world?  1``
so its not null i guess.

and the docs say " In the editor many Worlds exist: The level being edited, each PIE instance, each editor tool which has an interactive rendered viewport, and many more." https://docs.unrealengine.com/en-US/API/Runtime/Engine/Engine/UWorld/index.html

I already have a vanilla WebSockets version, but I was hoping I could use SocketCluster since it seems robust and has all of the surrounding features already implemented.
In my other version I have made a fairly simple ondisconnect which triggers when a server goes down, don't really see why timers would be essential here, but I understand. The property changing is just a simple explanation of a basic feature to give an example, the main feature being toggling play mode on n engines in the local network, which is obviously impossible at the moment with socketcluster.
Thank you for the explanation

**Comment by SloppyShovel** [comment]
If there is a world it should just work,

Maybe it needs some more checking, if you don't get the error, then it the world is not the error,
